### ISSUE TITLE
LinkedIn link and other don't export in PDF in Obsidian

### ISSUE THREAD

**Issue by Leaxius** [BingyanStudio/LapisCV#35]
Hello, thank you for your templates, very useful!
Unfortunately links such as the LinkedIn one do not work when exporting to PDF using Obsidian... See example below

[template-en2.pdf](https://github.com/user-attachments/files/19814145/template-en2.pdf)

**Comment by jiz4oh** [comment]
+1. 导出的 pdf 中链接无法点击，1.0 的时候是可以的

**Comment by Hihoshi** [comment]
typora使用这个模板同样会导致导出的pdf无法点击链接，甚至文字都无法选中

**Comment by Hihoshi** [comment]
> +1. obsidian 导出的 pdf 中链接无法点击，1.0 的时候是可以的

我解决了这个问题，移除main.css当中的这行就能解决问题
```css
a {
    filter: brightness(1.3) hue-rotate(-10deg);  /*删除这行*/
}
```
